name = "BigRationals"
uuid = "4b135b7f-1e8f-46e2-b4fa-ae0bd8ae44fd"
authors = ["Lionel Zoubritzky lionel.zoubritzky@gmail.com"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
